# Generated by Django 3.2.7 on 2021-10-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0002_auto_20211016_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
