# Generated by Django 3.2.7 on 2021-10-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0003_rename_size_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('alt', models.CharField(max_length=20, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyp.color')),
            ],
        ),
    ]
