# Generated by Django 3.2.7 on 2021-10-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0004_productthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ManyToManyField(to='pyp.ProductThumbnail'),
        ),
    ]
