# Generated by Django 3.2.7 on 2021-10-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='costomer',
            new_name='customer',
        ),
    ]
