# Generated by Django 3.2.7 on 2021-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyp', '0007_rename_costomer_wishlist_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
